const { model, Schema } = require('mongoose')
const User = new Schema({
  _id: { type: String },
  blacklist: { type: Boolean, default: false },
  userExempt: { type: Boolean, default: false },
  blacklistReason: { type: String, default: null },
  rep: { type: Number, default: 0 },
  bugsReported: { type: Number, default: 0 },
  repTime: { type: String, default: '000000000000' },
  gifban: { type: String, default: '' },
  cor: { type: String, default: '' },
  vip: { type: Boolean, default: false },
  strike: { type: Number, default: 0 },
  staff: { type: Boolean, default: false },
  backgroundsHas: { type: Array, default: [] },
  backgroundsActive: { type: Number, default: 0 },
  timeMarried: { type: Number, default: 0 },
  userMarried: { type: String, default: 'null' },
  isMarried: { type: Boolean, default: false },
  about: { type: String, default: 'null' },
  coins: { type: Number, default: 0 },
  daily: { type: Number, default: 0 },
  bank: { type: Number, default: 0 },
  xp: { type: Number, default: 1 },
  level: { type: Number, default: 1 },
  nextLevel: { type: Number, default: 100 },
  ExpId: { type: String, default: 'null' },
  ExpUser: { type: String, default: 'null' },
})

module.exports = model('Users', User)
